[cmob 1324] added chat adapter
DavitTsiskarashvili/Space-Chat-App pull request #4
Opened 2023-04-25 10:37 UTC by DavitTsiskarashvili

https://spaceneobank.atlassian.net/browse/CMOB-1324

2023-04-26 09:02 UTC, AnaRusadze requested changes
- ბეიზ ფრაგმენტი უნდა იყოს presentation -> base ში
- chatFragment და chatViewModel უნდა იყოს შესაბამისად presentation ui და presentation vm (viewmodel) ში
- ადაპტერი უნდა დარჩეს ui-ში

2023-04-26 09:02 UTC, AnaRusadze commented on app/src/main/java/com/example/spacechatapp/MainActivity.kt
>  class MainActivity : AppCompatActivity() {
ჯობია, რომ MainActivity-ს სახელში მიუთითო ზუსტად რისი ექთივითია. მეინის სახელს არ ვტოვებთ ხოლმე აპლიკაციაში. იგივე მეინვიუმოდელსაც. და ფექეჯებშიც გაანაწილე ui -> viewmodel ში.
p.s viewmodel შეგიძლია შეამოკლო და vm დაწერო

2023-04-26 09:02 UTC, AnaRusadze commented on app/src/main/java/com/example/spacechatapp/MainActivity.kt
> -            add(R.id.bottomFragment, BottomFragment())
ბოთომის დამატება რატომ წაშალე?

2023-04-26 09:02 UTC, AnaRusadze commented on app/src/main/java/com/example/spacechatapp/common/extensions/TextViewExtension.kt
> +    this.backgroundTintList = ColorStateList.valueOf(this.context.getColor(color))
თუ იმიჯვიუსთვისაც და ტექსტვიუსთვისაც გჭირდება ტინტის ექსთენშენი, შეგიძლია View.-ის ექსთენშენი გახადო და ტექსტვიუზეც გამოიყენებ და იმიჯვიუზეც

პატარა შენიშვნა, მაგრამ ქოლორის პარამეტრი Int თუ არის მიუთითე რომ რესურსს ელოდები, ანუ colorRes. იგივე შეგიძლია გაითვალისწინო drawableბზეც, როცა გამოიყენებ.

2023-04-26 09:02 UTC, AnaRusadze commented on app/src/main/java/com/example/spacechatapp/domain/model/MessageModel.kt
> +    val isSentBySender: Boolean
ყველა მესიჯს სენდერი აგზავნის ;დ სახელი ცოტა ალოგიკურია

2023-04-26 09:02 UTC, AnaRusadze commented on app/src/main/java/com/example/spacechatapp/presentation/ui/adapters/ChatAdapter.kt
> +    inner class ChatViewHolder(val binding: LayoutMessageItemBinding) :
ინერ კლასი არ გამოიყენო ვიუჰოლდერისთვის

2023-04-26 09:02 UTC, AnaRusadze commented on app/src/main/java/com/example/spacechatapp/presentation/ui/adapters/ChatAdapter.kt
> +package com.example.spacechatapp.presentation.ui.adapters
adapters ის მაგივრად adapter

2023-04-26 09:02 UTC, AnaRusadze commented on app/src/main/java/com/example/spacechatapp/presentation/ui/adapters/ChatAdapter.kt
> +                    user == UserType.Receiver && !message.isSentBySender
ლოგიკის შევუშავება უნდა შეძლო მხოლოდ იუზერ ტიპის გაგებით, message.isSentBySender ზედმეტია

2023-04-26 09:02 UTC, AnaRusadze commented on app/src/main/java/com/example/spacechatapp/presentation/ui/adapters/ChatAdapter.kt
> +                    with(-1f) {
გაიტანე ფრაივით კონსტანტ ცვლადებში 1 და -1

2023-04-26 09:02 UTC, AnaRusadze commented on app/src/main/java/com/example/spacechatapp/presentation/ui/adapters/ChatAdapter.kt
> +    }
გამეორებული კოდი შეგიძლია თავიდან აიცილო და ორი ფუნქციით დაწერო
ერთი-> setMessageScaleX(scale: Int)
მეორე -> setMessageColor(colorRes: Int)

2023-04-26 09:02 UTC, AnaRusadze commented on app/src/main/res/drawable/custom_edittext.xml
> +</shape>
სახელი უნდა გადაარქვა

2023-04-26 09:18 UTC, DavitTsiskarashvili commented on app/src/main/java/com/example/spacechatapp/MainActivity.kt
>  class MainActivity : AppCompatActivity() {
done

2023-04-26 09:18 UTC, DavitTsiskarashvili commented on app/src/main/java/com/example/spacechatapp/MainActivity.kt
> -            add(R.id.bottomFragment, BottomFragment())
1 ფრაგმენტი მაქვს

2023-04-26 09:21 UTC, DavitTsiskarashvili commented on app/src/main/java/com/example/spacechatapp/MainActivity.kt
> -            add(R.id.bottomFragment, BottomFragment())
დავამატე

2023-04-26 09:22 UTC, DavitTsiskarashvili commented on app/src/main/java/com/example/spacechatapp/presentation/ui/adapters/ChatAdapter.kt
> +package com.example.spacechatapp.presentation.ui.adapters
done

2023-04-26 09:30 UTC, DavitTsiskarashvili commented on app/src/main/res/drawable/custom_edittext.xml
> +</shape>
done

2023-04-26 09:36 UTC, DavitTsiskarashvili commented on app/src/main/java/com/example/spacechatapp/common/extensions/TextViewExtension.kt
> +    this.backgroundTintList = ColorStateList.valueOf(this.context.getColor(color))
done

2023-04-26 09:37 UTC, DavitTsiskarashvili commented on app/src/main/java/com/example/spacechatapp/presentation/ui/adapters/ChatAdapter.kt
> +    inner class ChatViewHolder(val binding: LayoutMessageItemBinding) :
done

2023-04-26 09:43 UTC, DavitTsiskarashvili commented on app/src/main/java/com/example/spacechatapp/presentation/ui/adapters/ChatAdapter.kt
> +                    with(-1f) {
done

2023-04-26 10:56 UTC, DavitTsiskarashvili commented on app/src/main/java/com/example/spacechatapp/presentation/ui/adapters/ChatAdapter.kt
> +    }
done

2023-04-26 11:06 UTC, DavitTsiskarashvili commented on app/src/main/java/com/example/spacechatapp/domain/model/MessageModel.kt
> +    val isSentBySender: Boolean
changed to isSentFromTop (ფრაგმენტის კონტეინერის გამო)

2023-04-26 12:27 UTC, DavitTsiskarashvili commented on app/src/main/java/com/example/spacechatapp/presentation/ui/adapters/ChatAdapter.kt
> +                    user == UserType.Receiver && !message.isSentBySender
done

2023-04-26 12:57 UTC, gioqemoklidze commented on app/src/main/java/com/example/spacechatapp/presentation/base/BaseFragment.kt
> +    abstract fun viewModelClass() : Class<VM>
ეხლა ამის აქ გამოტანას დიდად მნიშვნელობა არააქ მარა როცა di ს დაამატებ მერე უკვე ვიუმოდელის ამოღება სრულიად ბეიზში გადმოაგდე

2023-04-26 13:08 UTC, DavitTsiskarashvili commented on app/src/main/java/com/example/spacechatapp/presentation/base/BaseFragment.kt
> +    abstract fun viewModelClass() : Class<VM>
გავითვალისწინებ

2023-04-26 13:11 UTC, gioqemoklidze requested changes

2023-04-26 13:11 UTC, gioqemoklidze commented on app/src/main/res/drawable/message_edittext.xml
> +<?xml version="1.0" encoding="utf-8"?>
სახელში მეტი კონკრეტიკა რა რესურსია ბექგრაუნდია უბრალო შეიფია თუ რაარის

2023-04-26 13:11 UTC, gioqemoklidze commented on app/src/main/java/com/example/spacechatapp/ChatActivity.kt
> +class ChatActivity : AppCompatActivity() {
ფრეზენთეიშენში გადააგდე

2023-04-26 13:11 UTC, gioqemoklidze commented on app/src/main/java/com/example/spacechatapp/presentation/ui/ChatFragment/ChatViewModel.kt
> +package com.example.spacechatapp.presentation.ui.ChatFragment
ფექიჯები ესე დაალაგე presentation/chat_fragment/ui/ფრაგმენტი ჩააგდე აქ 
presentation/chat_fragment/vm/ვიუმოდელი ჩააგდე აქ 
presentation/chat_fragment/adapters/ადაპტერი ჩაადე აქ

2023-04-26 13:22 UTC, DavitTsiskarashvili commented on app/src/main/java/com/example/spacechatapp/ChatActivity.kt
> +class ChatActivity : AppCompatActivity() {
done

2023-04-26 13:22 UTC, DavitTsiskarashvili commented on app/src/main/java/com/example/spacechatapp/presentation/ui/ChatFragment/ChatViewModel.kt
> +package com.example.spacechatapp.presentation.ui.ChatFragment
done

2023-04-26 13:23 UTC, DavitTsiskarashvili commented on app/src/main/res/drawable/message_edittext.xml
> +<?xml version="1.0" encoding="utf-8"?>
done

2023-04-26 13:45 UTC, gioqemoklidze approved these changes

2023-04-27 13:26 UTC, bchmsl requested changes

2023-04-27 13:26 UTC, bchmsl commented on app/src/main/java/com/example/spacechatapp/presentation/chat_screen/adapter/ChatAdapter.kt
> +        @SuppressLint("DiffUtilEquals")
ამის სოლუშენს თუ მოიფიქრებ, ჯენერიკად როგორ გააკეთო ისე, რომ equals() გადატვირთო, კარგი იქნება.

2023-04-27 13:26 UTC, bchmsl commented on app/src/main/java/com/example/spacechatapp/presentation/chat_screen/adapter/ChatAdapter.kt
> +        }
ეს ფუნქცია ისე გადააკეთე, რომ კონკრეტული იმპლემენტაციის ნაცვლად ზოგადად scale და color-ის შეცვლას მოარგო და ამ ობიექტებზე უბრალოდ გამოიძახო

2023-05-01 13:24 UTC, DavitTsiskarashvili commented on app/src/main/java/com/example/spacechatapp/presentation/chat_screen/adapter/ChatAdapter.kt
> +        @SuppressLint("DiffUtilEquals")
ჰეშკოდების ნაცვლად რეფერენსებს ვადარებ და ჯერენიკის საჭიროება აღარაა

2023-05-01 13:24 UTC, DavitTsiskarashvili commented on app/src/main/java/com/example/spacechatapp/presentation/chat_screen/adapter/ChatAdapter.kt
> +        }
done, but on a different branch. So you will see it in the next PR :D

2023-05-01 13:30 UTC, Gio481 commented on app/src/main/java/com/space/chatApp/presentation/base/BaseAdapter.kt
> +    inner class BaseViewHolder(private val binding: VB) : RecyclerView.ViewHolder(binding.root) {
ინერ კლასი არ უნდა გამოიყენო მემორი ლიკს გამოიწვევს

2023-05-01 13:33 UTC, Gio481 requested changes

2023-05-01 13:33 UTC, Gio481 commented on app/src/main/java/com/space/chatApp/presentation/base/BaseAdapter.kt
> +    inner class BaseViewHolder(private val binding: VB) : RecyclerView.ViewHolder(binding.root) {
და ამ ბეის ადაპტერის გაკეთებას რა აზრის აქვს, არც იყნებ ხო

2023-05-01 13:33 UTC, Gio481 commented on app/src/main/java/com/space/chatApp/presentation/chat_screen/adapter/ChatAdapter.kt
> +}
წასაშლელია ეს

2023-05-01 13:33 UTC, Gio481 commented on app/src/main/res/drawable/shp_message_edittext.xml
> +</shape>
ღადაობ ? კიდე სტატიკურად გიწერია ფერები და ზომები

2023-05-01 13:33 UTC, Gio481 commented on app/src/main/res/layout/fragment_chat.xml
>          android:id="@+id/rvChatSender"
chatRecyclerView აიდებიი

2023-05-01 13:33 UTC, Gio481 commented on app/src/main/res/layout/layout_message_item.xml
>          android:id="@+id/tvMessage"
შასწორე ყველა აიდი

2023-05-01 13:34 UTC, DavitTsiskarashvili commented on app/src/main/java/com/space/chatApp/presentation/base/BaseAdapter.kt
> +    inner class BaseViewHolder(private val binding: VB) : RecyclerView.ViewHolder(binding.root) {
ვიყენებ, უბრალოდ შემდეგ ბრენჩზე ავამუშავე

2023-05-01 13:35 UTC, DavitTsiskarashvili commented on app/src/main/java/com/space/chatApp/presentation/chat_screen/adapter/ChatAdapter.kt
> +}
მართალი ხარ, შემდეგ ბრენჩზე წავშალე (ცოტა ავურიე ბრენჩები გუშინ და უკან დაბრუნება აღარ მინდა. შემდეგ ფულ რიქვესთში ნახავ რომ წაშლილია რა პორ ფავორ :D

2023-05-01 13:37 UTC, DavitTsiskarashvili commented on app/src/main/res/drawable/shp_message_edittext.xml
> +</shape>
აუ გუშინ რომ წამეშალა კოდები და ძველი ვერსიები დავაბრუნე მაგის ბრალია. მაგის გასწორება გამომრჩა :( გავასწორე

2023-05-01 13:43 UTC, DavitTsiskarashvili commented on app/src/main/res/layout/fragment_chat.xml
>          android:id="@+id/rvChatSender"
done

2023-05-01 13:44 UTC, DavitTsiskarashvili commented on app/src/main/res/layout/layout_message_item.xml
>          android:id="@+id/tvMessage"
done done done. ყველაფერი გავასწორე ახალ პრ-ში. შემდეგზე სწორ ბრენჩზევე გავასწორებ ხოლმე ახლა მაპატიეთ :D

2023-05-01 17:45 UTC, merged